name: 'Terraform CI'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Configure AWS Credentials.
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    # Checkout do código no runner do GitHub Actions.
    - name: Checkout code
      uses: actions/checkout@v2

    # Configura o Terraform CLI.
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Inicializa o Terraform.
    - name: Terraform Init
      run: |
        terraform init

    # Executa o terraform plan e salva os outputs.
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -out=tfplan

    # Aplica as mudanças usando terraform apply.
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform apply "tfplan"

    # Opcional: Destruir infraestrutura para PRs ou branches não principais.
    - name: Terraform Destroy
      if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
      run: |
        terraform destroy -auto-approve

    # Adicione mais passos conforme necessário.
