name: 'Terraform AWS Management'

on:
  workflow_dispatch:

jobs:
  terraform-management:
    name: 'Terraform Management'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Terraform Init, Plan, Apply e Destroy para o módulo EC2
      - name: Setup Terraform EC2
        run: |
          cd module/ec2
          terraform init
          terraform plan -var-file="configs/ec2.tfvars" -out=ec2.tfplan
          terraform apply "ec2.tfplan"
          terraform destroy -var-file="configs/ec2.tfvars" -auto-approve

      # Terraform Init, Plan, Apply e Destroy para o módulo S3
      - name: Setup Terraform S3
        run: |
          cd module/s3
          terraform init
          terraform plan -var-file="configs/bucket-s3-1.tfvars" -out=s3.tfplan
          terraform apply "s3.tfplan"
          terraform destroy -var-file="configs/bucket-s3-1.tfvars" -auto-approve